version: "3"
services:
  phonebook:
   image: phonebook:kate
   links:
     - database
   ports:
     - "8084:8080"
   environment:
     SERVICE_PORT: "8080"
     DB_HOST: "database"
     DB_PORT: "3306"
     DB_USERNAME: admin
     DB_PASSWORD: admin_password
     DB_NAME: phone_numbers
     AUTH_TOKEN: laba

  database:
    image: docker.io/mysql:8
    ports:
      - "33062:3306"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin_password
      MYSQL_DATABASE: phone_numbers
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
